services:
  mysql:
    container_name: postgres_picpay
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: postgres
      POSTGRES_DB: picpay
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    container_name: pgadmin4_picpay
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test.test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "3333:80"

volumes:
  postgres_data: {}